parameters:

services:
    sym3auth_demo.event.jwt_created_listener:
        class: UserBundle\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
        calls:
            - [setExtendedTokenTtl, ["%jwt_token_ttl%"]]

    sym3auth_demo.event.jwt_decoded_listener:
        class: UserBundle\EventListener\JWTDecodedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }

    # sym3auth_demo.event.jwt_response_listener:
    #     class: UserBundle\EventListener\JWTResponseListener
    #     tags:
    #         - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
